/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.bean.Cliente;

/**
 *
 * @author Vanessa
 */
public class MainView extends javax.swing.JFrame {
    
    private ClienteController clienteController = new ClienteController();

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        configurarMain();
        
        Cliente cliente = new Cliente();
        DefaultTableModel modeloTabelaClientes = (DefaultTableModel) jTableClientes.getModel();
        
        final MaskFormatter cpf, data, telefone;
        
        try {
            cpf = new MaskFormatter("###.###.###-##");
            cpf.setPlaceholder("111.111.111-11");
            cpf.install(txtCPF);
            
            telefone = new MaskFormatter("(##) ####-####");
            telefone.setPlaceholder("(dd) 1111-1111");
            telefone.install(txtTelefone);
            
            data = new MaskFormatter("##/##/####");
            data.setPlaceholder("dd/mm/aaaa");
            data.install(txtAniversario);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarMain = new javax.swing.JToolBar();
        btnInicial = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        btnListarClientes = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jPaneInicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelCadastrarCliente = new javax.swing.JPanel();
        labelCliente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAniversario = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jPanelListarClientes = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBarMain.setRollover(true);

        btnInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/10724474101553771553-32.png"))); // NOI18N
        btnInicial.setText("Inicial");
        btnInicial.setFocusable(false);
        btnInicial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInicial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicialActionPerformed(evt);
            }
        });
        jToolBarMain.add(btnInicial);

        btnCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/2452193471553771536-32.png"))); // NOI18N
        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.setFocusable(false);
        btnCadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });
        jToolBarMain.add(btnCadastrarCliente);

        btnListarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/13442522861553771544-32.png"))); // NOI18N
        btnListarClientes.setText("Listar Clientes");
        btnListarClientes.setFocusable(false);
        btnListarClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListarClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClientesActionPerformed(evt);
            }
        });
        jToolBarMain.add(btnListarClientes);

        jPanelMain.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Inicial");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Trabalho para a disciplina Programação Comercial II do curso Técnico em Informática \ndo Colégio Politécnico/UFSM. \n\nEste software está sendo desenvolvido no padrão SDI utilizando card layout. \n\nChangelog:\n19/11/2019 -> adicionado changelog, funcionalidade de busca na tela Listar Clientes, \ntransaction adicionado aos métodos create e update, repositório adicionado ao Github; ");
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPaneInicialLayout = new javax.swing.GroupLayout(jPaneInicial);
        jPaneInicial.setLayout(jPaneInicialLayout);
        jPaneInicialLayout.setHorizontalGroup(
            jPaneInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneInicialLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        jPaneInicialLayout.setVerticalGroup(
            jPaneInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneInicialLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jPanelMain.add(jPaneInicial, "card2");

        jPanelCadastrarCliente.setPreferredSize(new java.awt.Dimension(500, 246));

        labelCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCliente.setText("Cadastrar Cliente");

        jLabel3.setText("Nome completo");

        jLabel4.setText("E-mail");

        jLabel5.setText("CPF");

        txtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPFFocusGained(evt);
            }
        });

        jLabel6.setText("Telefone");

        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
        });

        jLabel7.setText("Data Aniversário");

        txtAniversario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAniversarioFocusGained(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setText("id");
        txtId.setToolTipText("");
        txtId.setEnabled(false);

        javax.swing.GroupLayout jPanelCadastrarClienteLayout = new javax.swing.GroupLayout(jPanelCadastrarCliente);
        jPanelCadastrarCliente.setLayout(jPanelCadastrarClienteLayout);
        jPanelCadastrarClienteLayout.setHorizontalGroup(
            jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarClienteLayout.createSequentialGroup()
                .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrarClienteLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanelCadastrarClienteLayout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))))
                    .addComponent(txtNome)
                    .addComponent(txtEmail)
                    .addGroup(jPanelCadastrarClienteLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanelCadastrarClienteLayout.createSequentialGroup()
                                .addComponent(labelCliente)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCadastrarClienteLayout.setVerticalGroup(
            jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarClienteLayout.createSequentialGroup()
                .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCliente)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAniversario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25))
        );

        jPanelMain.add(jPanelCadastrarCliente, "card3");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Clientes");

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Nome", "E-mail", "CPF", "Telefone", "Data Aniversario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setToolTipText("");
        btnAtualizar.setEnabled(false);
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarClientesLayout = new javax.swing.GroupLayout(jPanelListarClientes);
        jPanelListarClientes.setLayout(jPanelListarClientesLayout);
        jPanelListarClientesLayout.setHorizontalGroup(
            jPanelListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarClientesLayout.createSequentialGroup()
                .addGroup(jPanelListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanelListarClientesLayout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        jPanelListarClientesLayout.setVerticalGroup(
            jPanelListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarClientesLayout.createSequentialGroup()
                .addGroup(jPanelListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarClientesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAtualizar)
                        .addComponent(btnExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelListarClientes, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        // TODO add your handling code here:
        labelCliente.setText("Cadastrar Cliente");
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        
        jPanelMain.add(jPanelCadastrarCliente);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicialActionPerformed
        // TODO add your handling code here:
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        
        jPanelMain.add(jPaneInicial);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_btnInicialActionPerformed

    private void btnListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClientesActionPerformed
        // TODO add your handling code here:
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        
        jPanelMain.add(jPanelListarClientes);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_btnListarClientesActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        if(!txtId.getText().isEmpty()){
            cliente.setId(Integer.parseInt(txtId.getText()));
        }
        
        if(validarCampos() == true){
            if(cliente.getId() == 0){
                clienteController.create(txtNome.getText(), txtEmail.getText(), txtCPF.getText(), txtTelefone.getText(), txtAniversario.getText());
            } else {
                clienteController.update(Integer.valueOf(txtId.getText()), txtNome.getText(), txtEmail.getText(), txtCPF.getText(), txtTelefone.getText(), txtAniversario.getText());
            }
            
            limparCamposCliente();
            this.getListaClientes();

            jPanelMain.removeAll();
            jPanelMain.repaint();
            jPanelMain.revalidate();

            jPanelMain.add(jPanelListarClientes);
            jPanelMain.repaint();
            jPanelMain.revalidate();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFFocusGained
        // TODO add your handling code here:
        txtCPF.setText("");
    }//GEN-LAST:event_txtCPFFocusGained

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        // TODO add your handling code here:
        txtTelefone.setText("");
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void txtAniversarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAniversarioFocusGained
        // TODO add your handling code here:
        txtAniversario.setText("");
    }//GEN-LAST:event_txtAniversarioFocusGained

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCamposCliente();
        
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        
        jPanelMain.add(jPaneInicial);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // TODO add your handling code here:
        btnAtualizar.setEnabled(true);
        btnExcluir.setEnabled(true);
        
        if(jTableClientes.getSelectedRow() != -1){
            txtId.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0).toString());
            txtNome.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 1).toString());
            txtEmail.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 2).toString());
            txtCPF.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 3).toString());
            txtTelefone.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 4).toString());
            txtAniversario.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        labelCliente.setText("Atualizar Cadastro");
        jPanelMain.removeAll();
        jPanelMain.repaint();
        jPanelMain.revalidate();
        
        jPanelMain.add(jPanelCadastrarCliente);
        jPanelMain.repaint();
        jPanelMain.revalidate();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(jTableClientes.getSelectedRow() != -1){
            clienteController.delete((int) jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        this.getListaClientes();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(txtBuscar.getText().equals("")){
            this.getListaClientes();
        } else {
            this.getListaClientePorNome();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInicial;
    private javax.swing.JButton btnListarClientes;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneInicial;
    private javax.swing.JPanel jPanelCadastrarCliente;
    private javax.swing.JPanel jPanelListarClientes;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBarMain;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JFormattedTextField txtAniversario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
    private void configurarMain(){
        this.setTitle("Gestão de Vendas");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        txtId.setText("");
        txtId.setVisible(false);
        
        this.getListaClientes();
    }
    
    public void limparCamposCliente(){
        txtId.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        txtCPF.setText("");
        txtTelefone.setText("");
        txtAniversario.setText("");
    }
    
    public boolean validarCampos(){
        boolean valido;
        if(txtNome.getText().equals("") || txtEmail.getText().equals("") || 
           txtCPF.getText().equals("") || txtTelefone.getText().equals("") || txtAniversario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
            valido = false;
        } else {
            valido = true;
        }
        return valido;
    }
    
    public void getListaClientes(){
        btnAtualizar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        DefaultTableModel modeloTabelaClientes = (DefaultTableModel) jTableClientes.getModel();
        modeloTabelaClientes.setNumRows(0);
        
        for (Cliente c : clienteController.read()) {
            modeloTabelaClientes.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getCpf(),
                c.getTelefone(),
                c.getDataAniversario()});
        }
    }
    
    public void getListaClientePorNome(){
        btnAtualizar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        DefaultTableModel modeloTabelaClientes = (DefaultTableModel) jTableClientes.getModel();
        modeloTabelaClientes.setNumRows(0);
        
        for (Cliente c : clienteController.getListaClientePorNome(txtBuscar.getText())) {
            modeloTabelaClientes.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getCpf(),
                c.getTelefone(),
                c.getDataAniversario()});
        }
    }
}
